#!/bin/bash

FOLDERS=("ui" "api-server")
PASSPHRASE_FILE=".gpg_passphrase"
PASSPHRASE=$(cat "$PASSPHRASE_FILE")

echo "Encrypting env"

for FOLDER in "${FOLDERS[@]}"; do
    echo "Encrypting .env.production in $FOLDER to .env.gpg"

    INPUT_FILE="./${FOLDER}/.env.production"
    OUTPUT_FILE="./${FOLDER}/.env.gpg"

    gpg --batch --yes -o "$OUTPUT_FILE" --passphrase "$PASSPHRASE" --symmetric "$INPUT_FILE"
    EXIT_CODE=$?

    if [ "$EXIT_CODE" -eq 0 ]; then
        echo "Encryption successful for $INPUT_FILE"
        git add "$OUTPUT_FILE" -f
    else 
        echo "Failed to encrypt $INPUT_FILE"
        exit 1
    fi
done
